version: '3'

services:
  frontend:
    build: ./client
    ports:
      - "3000:3000"
    env_file:
      - ./client/.env  # Load frontend environment variables
    depends_on:
      - backend

  backend:
    build: ./server
    ports:
      - "5000:5000"
    env_file:
      - ./server/.env  # Load backend environment variables
